### ISSUE TITLE
`AssertionError` in `GroverOptimizer.solve`

### ISSUE THREAD

**Issue by cqc-alec** [Qiskit/qiskit-optimization#16] opened 2021-01-28 17:12 UTC
### Information

- **Qiskit Aqua version**: 0.8.1
- **Python version**: 3.8.2
- **Operating system**: Ubuntu 20.04

### What is the current behavior?

Calling `GroverOptimizer.solve` results in an `AssertionError`.

### Steps to reproduce the problem

```
from qiskit.aqua import aqua_globals
aqua_globals.random_seed = 1
from qiskit.aqua import QuantumInstance
from qiskit.optimization.algorithms import GroverOptimizer
from qiskit.optimization.problems import QuadraticProgram
from qiskit.providers.aer import Aer
from qiskit.providers.aer.noise import NoiseModel, depolarizing_error
from qiskit.transpiler import PassManager
from qiskit.transpiler.passes import Unroller
from qiskit import BasicAer
from docplex.mp.model import Model

backend = BasicAer.get_backend('statevector_simulator')

model = Model()
x0 = model.binary_var(name='x0')
x1 = model.binary_var(name='x1')
x2 = model.binary_var(name='x2')
model.minimize(-x0+2*x1-3*x2-2*x0*x2-1*x1*x2)
qp = QuadraticProgram()
qp.from_docplex(model)

backend = Aer.get_backend("qasm_simulator")
noise_model = NoiseModel()
noise_model.add_all_qubit_quantum_error(depolarizing_error(0.01, 1), ['p', 'u'])
noise_model.add_all_qubit_quantum_error(depolarizing_error(0.05, 2), ['cx'])

pm = PassManager([Unroller(['cx', 'p', 'u'])])
qi = QuantumInstance(backend, pass_manager=pm, noise_model=noise_model, seed_simulator=2)

grover_optimizer = GroverOptimizer(6, num_iterations=3, quantum_instance=qi)
results = grover_optimizer.solve(qp)
```

Output:

```
Traceback (most recent call last):
  File "problem1.py", line 32, in <module>
    results = grover_optimizer.solve(qp)
  File "/home/alec/anaconda3/envs/tket38/lib/python3.8/site-packages/qiskit/optimization/algorithms/grover_optimizer.py", line 225, in solve
    v = self._twos_complement(int_v, n_value)
  File "/home/alec/anaconda3/envs/tket38/lib/python3.8/site-packages/qiskit/optimization/algorithms/grover_optimizer.py", line 312, in _twos_complement
    assert -2 ** n_bits <= v < 2 ** n_bits
AssertionError

```

### What is the expected behavior?

`results` should be populated

### Suggested solutions

?

**Comment by woodsp-ibm** [comment] 2021-01-28 17:23
@cqc-alec We are in the process of moving splitting Aqua so each application domain like optimization is in its own repo. Hence I transferred the issue here where we are now maintaining the code in readiness for next release.

**Comment by cqc-alec** [comment] 2021-01-28 17:27
OK, thanks! My issue looks like a duplicate of https://github.com/Qiskit/qiskit-aqua/issues/1409 which is marked fixed, but presumably the fix is not yet in a release.

**Comment by woodsp-ibm** [comment] 2021-01-28 17:36
The last release of Aqua was 0.8.1 a few days before this. If you want to see you can installed Aqua from a clone of the master branch of the repo there and run with that and see. (If you want to do this and need information on installing from source you can look here https://qiskit.org/documentation/contributing_to_qiskit.html#installing-from-source - I think the other elements are still compatible and it should just be question of installing Aqua).

**Comment by cqc-alec** [comment] 2021-01-29 09:08
@woodsp-ibm Thanks, yes I see. Rather than install from master I will await the next aqua release which should have the fix.

**Comment by woodsp-ibm** [comment] 2021-01-29 14:33
As the problem in this issue is apparently a duplicate of a bug already fixed I will close this issue then. If you find then problem persists after the next release then feel free to re-open this as needed.

**Closed by woodsp-ibm** 2021-01-29 14:33 UTC
